name: build

on: 
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Unshallow Fetch
      run: |
        git fetch --unshallow

    - name: Setup Node
      uses: actions/setup-node@v1.1.0

    - name: Resolve Dependencies
      run: yarn

    - name: Run Unit Tests with Coverage
      run: yarn test:ci
      env:
        CI: true

    - name: Cypress e2e Tests
      uses: cypress-io/github-action@v1
      with:
        # record: true
        #start: yarn start:instrumented
        start: yarn start
        command-prefix: 'percy exec -- yarn'
      env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Merge Coverage Reports
      run: |
        cp jest_coverage/coverage-final.json .nyc_output/coverage-unit-tests.json
        yarn nyc report --reporter=lcov --report-dir=.nyc_output

    - name: Test Coverage to Coveralls
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: .nyc_output/lcov.info

    - name: SonarCloud Report File Preparation
      run: |
        sed -i 's/\/home\/runner\/work\/bits-to-atoms\/bits-to-atoms\//\/github\/workspace\//g' .nyc_output/lcov.info

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Build
      run: yarn build

    - name: Generate Release
      uses: cycjimmy/semantic-release-action@v2.1.3
      id: semantic
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}

    - name: Update package.json if new Release Generated
      if: steps.semantic.outputs.new_release_published == 'true'
      run: |
        git config --global user.name ${{ secrets.GIT_USER_NAME }}
        git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
        git commit -am "package.json updated by semantic-release"
        git push

    - name: Configure the CNAME for GitHub Pages
      run: echo bitstoatoms.io > build/CNAME

    - name: Deploy GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.3.0
      with:
        build_dir: build
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}