name: build

on: 
  push:
    branches:
    - master

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1.1.0

    - name: Resolve Dependencies
      run: yarn

    - name: Build
      run: yarn build

    - name: Generate Release
      uses: cycjimmy/semantic-release-action@v2.1.3

    - name: Configure the CNAME
      run: yarn config-cname

    - name: Deploy GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.3.0
      with:
        build_dir: build

      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
    