name: build

on: 
  push:
    branches:
    - master

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1.1.0

    - name: Resolve Dependencies
      run: yarn

    - name: Run Tests with Coverage
      run: yarn test:ci
      env:
        CI: true

    - name: Coveralls
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: SonarCloud Scan
      working-directory: ./coverage
      run: sed -i 's/\/home\/runner\/work\/bits-to-atoms\/bits-to-atoms\//\/github\/workspace\//g' lcov.info
      working-directory: .
      run: sed -i 's/\/home\/runner\/work\/bits-to-atoms\/bits-to-atoms\//\/github\/workspace\//g' test-report.xml
      uses: SonarSource/sonarcloud-github-action@v1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Build
      run: yarn build

    - name: Generate Release
      uses: cycjimmy/semantic-release-action@v2.1.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}

    - name: Configure the CNAME for GitHub Pages
      run: echo bitstoatoms.io > build/CNAME

    - name: Deploy GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.3.0
      with:
        build_dir: build
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
    