name: build

on: 
  push:
    branches:
    - master

jobs:
  pipeline:
    runs-on: ubuntu-16.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Unshallow Fetch
      run: |
        git fetch --unshallow

    - name: Setup Node
      uses: actions/setup-node@v1.1.0

    - name: Resolve Dependencies
      run: yarn

    - name: Run Unit Tests with Coverage
      run: yarn test:ci
      env:
        CI: true

    - name: Cypress e2e Tests
      uses: cypress-io/github-action@v1.16.1
      with:
        record: true
        start: yarn start:instrumented
      env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate Cypress Coverage
      run: yarn cypress:coverage

    - name: Merge Coverage Reports
      run: |
        cp coverage/coverage-final.json .nyc_output/coverage-unit-tests.json
        yarn nyc merge .nyc_output\ .nyc_output\coverage.json
        yarn nyc report --reporter=lcov --report-dir=.nyc_coverage

    - name: Test Coverage to Coveralls
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: .nyc_coverage/lcov.info

    - name: SonarCloud Report File Preparation
      run: |
        sed -i 's/\/home\/runner\/work\/bits-to-atoms\/bits-to-atoms\//\/github\/workspace\//g' .nyc_coverage/lcov.info

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Build
      run: yarn build

    - name: Generate Release
      uses: cycjimmy/semantic-release-action@v2.1.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}

    - name: Configure the CNAME for GitHub Pages
      run: echo bitstoatoms.io > build/CNAME

    - name: Deploy GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.3.0
      with:
        build_dir: build
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
    