name: build

on: 
  push:
    branches:
    - master

jobs:
  test-release: 
    runs-on: ubuntu-16.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Unshallow Fetch
      run: |
        git fetch --unshallow

    - name: Setup Node
      uses: actions/setup-node@v1.1.0

    - name: Resolve Dependencies
      run: yarn
  
    - name: Generate Release
      uses: cycjimmy/semantic-release-action@v2.1.3
      id: semantic
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}

    - name: Update package.json when new release published
      if: steps.semantic.outputs.new_release_published == 'true'
      run: |
        git config --global user.name ${{ secrets.GIT_USER_NAME }}
        git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
        git commit -am "package.json updated by semantic-release"
        git push
